runtime: python39

handlers:
# Serve the main page
- url: /
  static_files: index.html
  upload: index.html

# Serve CSS files
- url: /(.*\.css)
  static_files: \1
  upload: .*\.css$
  expiration: "7d"

# Serve JavaScript files
- url: /(.*\.js)
  static_files: \1
  upload: .*\.js$
  expiration: "7d"

# Serve all other static files
- url: /(.*)
  static_files: \1
  upload: (.*)

# Skip files that shouldn't be uploaded
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.md$
- ^(.*/)?code\.ts$ 